/**
 * Shared utility functions and constants
 */

import profile from '@/data/profile.json';

// Site configuration
export const SITE_URL = 'https://spazzero.github.io';
export const AUTHOR_NAME = profile.name;
/**
 * No X account yet.
 *
 * An empty handle makes Next omit `twitter:site` and `twitter:creator`
 * entirely rather than emit empty tags, which is why `verify-export` treats
 * them as required only once a page declares one. This stays an exported empty
 * string rather than being commented out because `src/lib/metadata.ts` imports
 * it. Set it to '@handle' when the account exists and both tags fill in, at
 * which point the verifier starts enforcing them on every page again.
 */
export const TWITTER_HANDLE = '';
/**
 * The portrait. Used for JSON-LD `image`, where the value should be a picture
 * of the person, not a designed card.
 */
export const SITE_IMAGE_PATH = '/images/me.jpg';
export const SITE_IMAGE_DIMENSIONS = {
  width: 1024,
  height: 1024,
} as const;

/**
 * The share card, generated by `npm run og` and committed to `public/`.
 *
 * Every page points at this one path explicitly. Next's `opengraph-image`
 * file convention is not used: a route-level `openGraph` object replaces the
 * inherited one wholesale, which left every subpage with no image at all, and
 * the metadata route emits an extensionless file that GitHub Pages serves as
 * application/octet-stream.
 */
export const SHARE_IMAGE_PATH = '/og.png';
export const SHARE_IMAGE_DIMENSIONS = {
  width: 1200,
  height: 630,
} as const;

// Canonical one-line bio, shared across page metadata, OpenGraph, and JSON-LD.
export const SITE_DESCRIPTION =
  'DCM Analyst & Data Engineer Intern at Covalent Capital, based in Singapore.';

// Image dimension constants
export const PROJECT_IMAGE = {
  width: 600,
  height: 400,
} as const;

/**
 * Formats a date string to a human-readable format.
 * Parses as UTC to avoid timezone shifts.
 */
export function formatDate(dateStr: string): string {
  if (!dateStr) return '';
  // Parse as UTC to avoid timezone shifts
  const date = new Date(`${dateStr}T12:00:00`);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}
